# Generated by Django 3.0.2 on 2020-01-27 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FilePathField(path='media/video/', verbose_name='video_url')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('load_at', models.DateTimeField(auto_now=True)),
                ('premium', models.BooleanField(default=False)),
            ],
        ),
    ]
